# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: KBOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

 
      
      - name: Run test
        run: make test

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.GIT_USERNAME }}
        run: make image push




